apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: watt-8b-vllm-inference
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi